{% set name = "awsebcli" %}
{% set version = "3.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07be62114080f26211036e0eb0b99eadb4becfe1f341bc1ea5f0051cba3c4641

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - botocore >=1.35
    - cement ==2.10.14
    - colorama >=0.4.6
    - pathspec >=0.10.1
    - python-dateutil >=2.1
    - requests >=2.31
    - semantic_version >=2.10.0
    - termcolor >=2.4.0
    - wcwidth >=0.2.13
    - PyYAML >=5.3.1
    - urllib3 >=1.26.5
    - blessed >=1.20.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ebcli
  commands:
    - eb --help
    - ebp --help

about:
  home: http://aws.amazon.com/elasticbeanstalk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Command Line Interface for AWS EB.

extra:
  recipe-maintainers:
    - hadim
