{% set name = "awsebcli" %}
{% set version = "3.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70c247f9d54b8071d7550127e665a42a837f72812c5a1749ddb17104fbdba8db

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - blessed >=1.9.5
    - botocore >=1.15
    - cement ==2.10.12,<3
    - colorama >=0.4
    - future >=0.16.0
    - pathspec >=0.5.9
    - python-dateutil >=2.1
    - requests >=2.20.1
    - setuptools >=20.0
    - semantic_version >=2.8.5
    - six >=1.11.0
    - termcolor >=1.1.0
    - urllib3 >=1.24.1
    - wcwidth >=0.1.7
    - PyYAML >=5.3.1

test:
  imports:
    - ebcli
  commands:
    - eb
    - ebp

about:
  home: http://aws.amazon.com/elasticbeanstalk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Command Line Interface for AWS EB.

extra:
  recipe-maintainers:
    - hadim
