context:
  name: awsebcli
  version: 3.21.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/awsebcli-${{ version }}.tar.gz
  sha256: 07be62114080f26211036e0eb0b99eadb4becfe1f341bc1ea5f0051cba3c4641
  patches:
    - fix-deps.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - eb=ebcli.core.ebcore:main
      - ebp=ebcli.core.ebpcore:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=20.0
  run:
    - python >=${{ python_min }}
    - botocore <1.36.0,>=1.35.0
    - cement ==2.10.12
    - colorama <0.5,>=0.4.6
    - pathspec ==0.10.1
    - python-dateutil <3.0.0,>=2.1
    - requests <3,>=2.31
    - setuptools >=20.0
    - semantic_version <2.11,>=2.10.0
    - termcolor <3,>=2.4.0
    - wcwidth <0.3,>=0.2.13
    - pyyaml <6.1,>=5.3.1
    - urllib3 <2,>=1.26.5
    - ${{ "blessed >=1.20.0" if not win }}
    - ${{ "pywin32 ==223" if win }}

tests:
  - python:
      imports:
        - ebcli
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - eb --help
      - ebp --help

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Command Line Interface for AWS EB.
  homepage: http://aws.amazon.com/elasticbeanstalk/

extra:
  recipe-maintainers:
    - hadim
