context:
  name: awsebcli
  version: "3.23.3"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/awsebcli-${{ version }}.tar.gz
  sha256: 9fe174f19882cb345e412feb8916c3202cc07e05766317bf7f4aa3b1f5f0e5cb
  patches:
    - fix-deps.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - eb=ebcli.core.ebcore:main
      - ebp=ebcli.core.ebpcore:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=20.0
  run:
    - python >=${{ python_min }}
    - botocore >=1.35.0,<2
    - cement ==2.10.12
    - colorama >=0.4.6,<0.5
    - pathspec ==0.12.1
    - python-dateutil >=2.1,<3.0.0
    - requests <3,>=2.31
    - setuptools >=20.0
    - semantic_version <2.11,>=2.10.0
    - termcolor <3,>=2.4.0
    - wcwidth <0.3,>=0.2.13
    - pyyaml <6.1,>=5.3.1
    - urllib3 <2,>=1.26.5
    - blessed >=1.20.0
    - ${{ "pywin32 ==223" if win }}
    - packaging =24.2,<25.0

tests:
  - python:
      imports:
        - ebcli
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - eb --help
      - ebp --help

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Command Line Interface for AWS EB.
  homepage: https://github.com/aws/aws-elastic-beanstalk-cli
  documentation: http://aws.amazon.com/elasticbeanstalk/

extra:
  recipe-maintainers:
    - hadim
